// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:eda8de4e-9358-4e43-9e58-8d0060db9eb2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_n7KaF7Rgg",
    "aws_user_pools_web_client_id": "ojb1bf9mu712fjug2m5li55k5",
    "oauth": {},
    "aws_mobile_analytics_app_id": "b030a9fc3b4449928d43af4de62f2bf4",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://3cw5erhafngxhaekkaqtvxrfbq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
